#!/usr/bin/env python3

"""\
    One-line 24 Game
    ================

    By AnqurVanillapy (Dec 1, 2016)

    - In list comprehension
    - In map (slower)
"""

import random;print([random.randint(1,10)for i in range(4)])
# import random;print(list(map(lambda x: random.randint(1,10),range(4))))
