#!/usr/bin/env bash

################################################################################
#
# crmap
# =====
#
# A simple lookup table that only supports creation and read.  `cp' before use.
# Note that it would not handle any collisions.
#
# @author AnqurVanillapy
# @date 31 October 2017
# @version 0.1.1
################################################################################


function show_usage () {
    echo "Usage: crmap KEY [VALUE]"
    echo
    echo -e "\t\`crmap key value' for creation"
    echo -e "\t\`crmap key' for lookup"
}

if [[ -e "crmap" ]]; then
    crmap_path="./crmap"       # assume: in the repo
else
    crmap_path=$(which crmap)  # assume: already in $PATH or alias
fi

if [[ -z $crmap_path ]]; then
    echo "Please \`cp' this file before use"
    exit 1
fi

function crmap_add () {
    sed -i '$ d' $crmap_path
    echo -e "    \"$1\") echo \"$2\" ;;" >> $crmap_path
    echo    "    *) exit 1 ;;" >> $crmap_path
    echo    "esac" >> $crmap_path
}

if [[ $# -lt 1 || $# -gt 2 ]]; then
    show_usage
    exit 1
fi

if [[ $# -eq 2 ]]; then
    crmap_add $1 $2
    exit 0
fi

case "$1" in
esac
