#!/usr/bin/env bash

################################################################################
#
# gh-clone
# ========
#
# A simple command generator to clone a GitHub remote repo.
#
# Notice:
#   1. Run this script to configure HTTPS/SSH scheme option.
#
# @author AnqurVanillapy
# @date 28 April 2017
# @version 0.1.0
################################################################################

function _usage () {
    echo "Usage: $0 {https|ssh}"
    exit 1
}

function _generate () {
    echo "#!/usr/bin/env bash" > gh-clone
    echo "if [[ \"\$#\" != \"2\" ]]; then echo \"Usage: gh-clone user repo\" && exit 1; fi" >> gh-clone
    echo "git clone $GH_REPO_ADDR\$1/\$2.git" >> gh-clone
    chmod -f +x gh-clone
}

GH_REPO_ADDR="github.com"

if [[ "$#" == "1" ]]; then
    _scheme=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$_scheme" in
        "https")
            GH_REPO_ADDR="https://$GH_REPO_ADDR/"
            ;;
        "ssh")
            GH_REPO_ADDR="git@$GH_REPO_ADDR:"
            ;;
        *)
            _usage
            ;;
    esac
    _generate
else
    _usage
fi
