#!/usr/bin/env bash

################################################################################
#
# gh-add
# ======
#
# A simple command generator to add a GitHub remote repo
#
# Notice:
#   1. Run this script to enter the config, e.g. username and HTTPS/SSH option.
#
# @author AnqurVanillapy
# @date 22 December 2016
# @version 0.1.1
################################################################################

function _usage () {
    echo "Usage: $0 [https|ssh] [username]"
    exit 1
}

function _generate () {
    echo "#!/usr/bin/env bash" > gh-add
    echo "if [[ \"\$#\" != \"1\" ]]; then echo \"usage: gh-add [repo_name]\" && exit 1; fi" >> gh-add
    echo "git remote add origin $GH_REPO_ADDR/\$1.git" >> gh-add
    chmod -f +x gh-add
}

GH_REPO_ADDR="github.com"

if [[ "$#" == "2" ]]; then
    _scheme=$(echo "$1" | tr '[:upper:]' '[:lower:]')
    case "$_scheme" in
        "https")
            GH_REPO_ADDR="https://$GH_REPO_ADDR/$2"
            ;;
        "ssh")
            GH_REPO_ADDR="git@$GH_REPO_ADDR:$2"
            ;;
        *)
            _usage
            ;;
    esac
    _generate
else
    _usage
fi
