#!/usr/bin/env bash

################################################################################
#
# byteorder
# =========
#
# Print the byte order the system is using.
#
# @author AnqurVanillapy
# @date 6 August 2018
# @version 0.1.0
################################################################################

lscpu | grep "Byte Order"
