#!/usr/bin/env bash

################################################################################
#
# clcb
# ====
#
# Clean the clipboard, a good habit for privacy.
#
# @author AnqurVanillapy
# @date 7 April 2018
# @version 0.1.0
################################################################################

if [[ "$#" != "0" ]]; then echo "Usage: clcb" && exit 1; fi
echo -n | xsel -b
