#!/usr/bin/env bash

################################################################################
#
# curl-json
# =========
#
# Simple alias for testing JSON APIs.
#
# @author AnqurVanillapy
# @date 14 May 2017
# @version 0.1.0
################################################################################

function usage() {
    echo "Usage: curl-json method host single-quoted-data" && exit 1
}

if [[ "$#" != "3" ]]; then usage; fi

# Yup, I told ya it's just a simple alias :S
curl -H "Content-Type: application/json" -X "$1" -d "$3" "$2"
