#!/usr/bin/env bash

################################################################################
#
# filesz
# ======
#
# Get the (total) size of single or multiple files (or even directories).
#
# @author AnqurVanillapy
# @date 12 August 2017
# @version 0.1.0
################################################################################

_stat="stat --printf=%s"
s=0

case "$#" in
    "0")
        echo "Usage: filesz filename..." && exit 1
        ;;
    "1")
        $_stat $1
        ;;
    *)
        for arg in "$@"; do
            s=$((s + $($_stat $arg)))
        done
        echo "$s"
        ;;
esac
