#!/usr/bin/env bash

################################################################################
#
# fucklag
# =======
#
# Run a command forever, until it's done.
#
# WARN: No limits like timeout or upper bound.
#
# @author AnqurVanillapy
# @date 25 December 2016
# @version 0.1.1
################################################################################

GREEN='\033[0;32m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

_command="$@"
_count=1

function _usage () {
    echo "Usage: fucklag command [args...]"
    exit 1
}

if [[ "$#" = "0" ]]; then
    _usage
fi

while :
do
    echo -e "[${RED}${BOLD}fucklag${NC}] attempt #$_count"
    $_command
    if [[ "$?" = "0" ]]; then
        break
    fi
    ((_count++))
done

echo -e "[${GREEN}${BOLD}fucklag${NC}] Done at attempt #$_count"
