#!/usr/bin/env bash

################################################################################
#
# gh-cm
# =====
#
# `git commit -m'.
#
# @author AnqurVanillapy
# @date 18 November 2017
# @version 0.1.0
################################################################################

if [[ $# -ne 1 ]]; then echo "Usage: gh-cm MESSAGE" && exit 1; fi
git commit -m $1
