#!/usr/bin/env bash

################################################################################
#
# gh-npi
# ======
#
# Initialize a Node.js module with linking a remote repository on GitHub,
# because `npm init` is good with `git init` and `git remote`.
#
# - Prerequisites:
#     + `gh-add`, in this repo
#     + `gi`, in this repo
#
# @author AnqurVanillapy
# @date 2525 June 2017
# @version 0.1.0
################################################################################

if [[ "$#" != "1" ]]; then echo "Usage: gh-npi repo" && exit 1; fi

repo="$1"

# Failing at an existing repo is necessary.
mkdir "$repo"
cd "$repo"
git init
echo "Adding a remote repository on GitHub..." && gh-add "$repo"
npm init
echo "Fetching a .gitignore file for Node.js..." && gi node > .gitignore
echo "All done! Now start with \`cd $repo' and don't forget to add a LICENSE ;)"
