#!/usr/bin/env python3

"""\
    HTTP Host OK
    ============

    Is this an available HTTP host?  For checking availability of any proxy IPs.

    By AnqurVanillapy (Jun 17, 2017)

    1. TCP connection via socket
    2. Check if HTTPBasic Auth required
"""

import sys
from socket import *
import requests


# FIXME: HTTP as default, ignoring HTTPS, SOCKS, etc.
try:
    HOST, PORT = sys.argv[1:] if len(sys.argv) == 3 else (sys.argv[1], 80)
    ROUTE = sys.argv[3] if len(sys.argv) > 3 else ''
except:
    print('Usage: hhok host [port] [route]')
    sys.exit(1)

# Step 1.
with socket(AF_INET, SOCK_STREAM) as s:
    s.connect((HOST, int(PORT)))
    s.sendall(b'\n')    # bad request on purpose
    data = s.recv(1024)


try:
    data = data.decode('utf-8')
    assert(data[:4] == 'HTTP')
except:
    sys.exit(1)


# Step 2.
req = requests.get('http://{}:{}{}'.format(HOST, PORT, ROUTE))
try: assert(req.status_code != 401)
except: print('WARNING: HTTPBasic Auth required')
