#!/usr/bin/env bash

################################################################################
#
# holdon
# ======
#
# Just typed an extremely long command but not gonna hit the enter at that
# moment?  `holdon` helps to put that into the clipboard.  Although it pollutes
# the current clipboard content, it avoids checking the running shell and
# finding the location of its history files for appending, because it seems
# nontrivial :).
#
# @author AnqurVanillapy
# @date 17 August 2017
# @version 0.1.0
################################################################################

if [[ "$#" = "0" ]]; then echo "Usage: holdon command" && exit 1; fi

_cmd="$@"
echo -n "$_cmd" | xsel -b
