#!/usr/bin/env bash

################################################################################
#
# hpxy
# ====
#
# Namely `HTTP proxy', execute commands with temporary local $http_proxy.
#
# Note: `privoxy' as rerequisite.
#
# @author AnqurVanillapy
# @date 6 May 2017
# @version 0.2.0
################################################################################

if [[ $# -lt 1 ]]; then
    echo "usage: hpxy commands ..."
    exit 1
fi

function get_addr () {
    while read line; do
        for word in "listen-address"; do
            if [[ "$line" == *"$word"* ]]; then
                addr=$(echo -e "$line" | xargs | awk '{print $NF}')
                echo "http://$addr"
            fi
        done
    done
}

privoxy_conf="/etc/privoxy/config"
url=$(grep -v '^#' < "$privoxy_conf" | get_addr)

# Starting proxy and following commands...
export http_proxy=$url
privoxy --no-daemon $privoxy_conf &
$@
kill $!
