#!/usr/bin/env bash

################################################################################
#
# ischeme
# =======
#
# Pragmatic wrapper for `scheme` REPL.
#
# @author AnqurVanillapy
# @date 23 February 2018
# @version 0.1.0
################################################################################

# Shout out to this awesome completion file from bobbyno.
complurl="https://gist.githubusercontent.com/bobbyno/3325982/raw/fc0208d287e56adc12b4c76114fcd21a107082ad/mit_scheme_bindings.txt"
complfile="$HOME/.scheme_completion"

if [[ !(-e "$complfile") ]]; then
    echo "WARNING: Completion file \`$complfile' not found, try fetching..."
    curl -sL "$complurl" > "$complfile"
    echo >> "$complfile"    # EOF
fi

rlwrap -r -c -f "$complfile" scheme
