#!/usr/bin/env bash

################################################################################
#
# leinpi
# ======
#
# Namely `lein proxy install', install dependencies with local $http_proxy.
#
# Note: `privoxy' as rerequisite.
#
# @author AnqurVanillapy
# @date 6 May 2017
# @version 0.1.0
################################################################################

function get_addr () {
    while read line; do
        for word in "listen-address"; do
            if [[ "$line" == *"$word"* ]]; then
                addr=$(echo -e "$line" | xargs | awk '{print $NF}')
                echo "http://$addr"
            fi
        done
    done
}

privoxy_conf="/etc/privoxy/config"
url=$(grep -v '^#' < "$privoxy_conf" | get_addr)

# Starting proxy and `lein install'...
export http_proxy=$url
privoxy --no-daemon $privoxy_conf &
lein install $@
kill $!
