#!/usr/bin/env bash

################################################################################
#
# mathpng
# =======
#
# Convert LaTeX files into PNG images
#
# Dependencies:
#   - `latex'
#   - `dvipng'
#
# @author AnqurVanillapy
# @date 15 January 2017
# @version 0.1.0
################################################################################

function show_usage () {
    echo "Usage: mathpng infile outfile" && exit 1
}

if [[ "$#" != "2" ]]; then show_usage; fi

payload=$(cat "$1")

if [[ "$?" == "1" ]]; then exit 1; fi

article="\\documentclass{article}\\pagestyle{empty}\\begin{document}\[$payload\]\\end{document}"
tex_id="mathpng.$$"

echo "$article" > "$tex_id.tex"
latex "$tex_id" > /dev/null
dvipng -T tight -x 1200 -z 9 "$tex_id.dvi" -o "$2" 1> /dev/null 2> /dev/null
rm $tex_id.*
