#!/usr/bin/env bash

################################################################################
#
# meng
# ====
#
# Grep the definition of a certain errno from its man page.
#
# @author AnqurVanillapy
# @date 7 March 2018
# @version 0.1.0
################################################################################


function show_usage () {
    echo "Usage: meng ERRNO"
    exit 1
}

if [[ "$#" -ne "1" ]]; then
    show_usage
fi

errno_uc=$(echo "$1" | tr [a-z] [A-Z])
man errno | grep "$errno_uc"
