#!/usr/bin/env bash

################################################################################
#
# mkcv
# ====
#
# Make a CV, based on Markdown.
#
# Prerequisite: `markdown` (the Perl script written by John Gruber).
#
# @author AnqurVanillapy
# @date 12 August 2017
# @version 0.1.0
################################################################################

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo "Usage: mkcv [file|-l|--list] [theme]" && exit 1;
fi

# `github-markdown-css' by default.
declare -A THEMES

# Maps all theme names to their URLs.
THEMES[github]=https://raw.githubusercontent.com/sindresorhus/github-markdown-css/gh-pages/github-markdown.css

function list_themes () {
    echo "Available themes:"
    for i in "${!THEMES[@]}"; do
        echo "* $i"
    done
}

if [[ "$1" == "-l" || "$1" == "--list" ]]; then list_themes && exit; fi
if [[ -z "$2" ]]; then
    t=github
    echo "WANRING: No theme given, use \`github-markdown-css' by default" >&2
else
    t="$2"
fi

theme_url=${THEMES[$t]}
if [[ -z "$theme_url" ]]; then list_themes && exit 1; fi

style=$(curl -s "$theme_url")

read -r -d '' tmpl_header << EndOfHeader
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="initial-scale=1">
  <title>CV</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    $style

    /* Responsive. */
    .markdown-body {
      box-sizing: border-box;
      min-width: 200px;
      max-width: 980px;
      margin: 0 auto;
      padding: 45px;
    }

    @media (max-width: 767px) {
      .markdown-body {
        padding: 15px;
      }
    }
  </style>
</head>
<body class="markdown-body">
EndOfHeader

content=$(markdown "$1")

read -r -d '' tmpl_footer << EndOfFooter
</body>
</html>
EndOfFooter

echo "$tmpl_header$content$tmpl_footer" # better not to escape
