#!/usr/bin/env bash

################################################################################
#
# pedant
# ======
#
# Life of pedant.  My favorite flags for a specific C/C++ compiler.
#
# @author AnqurVanillapy
# @date 12 August 2018
# @version 0.1.0
################################################################################

if [[ $# -lt 1 ]]; then echo "Usage: pedant CXX [ARGS...]" && exit 1; fi
cxx=$1
shift
$cxx -Wall -Wextra -pedantic -Ofast -pthread $@
