#!/usr/bin/env bash

################################################################################
#
# ppjson
# ======
#
# Pretty-print JSON, just an alias of using `json.tool' in Python.
#
# @author AnqurVanillapy
# @date 3 June 2017
# @version 0.1.0
################################################################################

# Nothing special here I promise...
if [[ "$#" != "2" ]]; then echo "Usage: ppjson infile outfile" && exit 1; fi
python3 -m json.tool $1 $2
