#!/usr/bin/env bash

################################################################################
#
# pwgr
# ====
#
# Output the current working git repository, if any, going back by `cd $(pgwr)`
# conveniently.
#
# @author AnqurVanillapy
# @date 22 March 2018
# @version 0.1.0
################################################################################

function show_usage() {
    echo "Usage: pwgr [--query-depth|-d=32]" && exit 1
}

if [[ $# -gt 2 ]]; then show_usage; fi

depth=32

case $1 in
    -d=*|--query-depth=*)
        depth="${1#*=}"
        ;;
    "")
        ;;
    *)
        show_usage
        ;;
esac

for ((i = 0; i < $depth; i++)); do
    if [[ -d ".git" ]]; then pwd && exit; fi
    cd ../
done

exit 1
