#!/usr/bin/env bash

################################################################################
#
# sciconn
# =======
#
# Scientific Connection - Toggle SOCKS5 proxy
#
# > God use SOCKS5
#
# @author AnqurVanillapy
# @date 13 August 2016
# @version 0.0.1
################################################################################

proxy_mode=$(gsettings get org.gnome.system.proxy mode)
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

function usage () {
    echo "Usage:"
    echo "  sciconn"
    echo "  sciconn [-h|--help]"
    echo "  sciconn COMMAND"
    echo
    echo "Commands:"
    echo "  on          Turn on the SOCKS5 proxy"
    echo "  off         Turn it off"
    echo "  status      I am confused now"
}

function sciconn_on () {
    gsettings set org.gnome.system.proxy mode 'manual'
    echo -e "${GREEN}:D${NC} Scientific internet access via $socks_proxy"
}

function sciconn_off () {
    gsettings set org.gnome.system.proxy mode 'none'
    echo -e "${RED}:X${NC} Take care and behave yourself"
}

if [[ "$#" = "0" ]]; then
    if [[ $proxy_mode != "'manual'" ]]; then
        sciconn_on
    else
        sciconn_off
    fi
elif [[ "$#" = "1" ]]; then
    if [[ "$1" = "on" ]]; then
        sciconn_on
    elif [[ "$1" = "off" ]]; then
        sciconn_off
    elif [[ "$1" = "status" ]]; then
        if [[ $proxy_mode = "'manual'" ]]; then
            echo -e "${GREEN}:D${NC} On via $socks_proxy"
        else
            echo -e "${RED}:X${NC} Off"
        fi
    elif [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
        usage
    else
        echo "Invalid command: $1"
        echo
        usage
        exit 1
    fi
else
    usage
    exit 1
fi
