#!/usr/bin/env python3

"""\
toggxy
======

App Indicator for toggling Ubuntu proxy setting between `none` and `manual`,
that's it.

By AnqurVanillapy (Sep 3, 2017)
"""

import signal

# Set up `gi' version.
import gi
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')

from gi.repository import Gtk as gtk
from gi.repository import AppIndicator3 as appindicator
from gi.repository import Gio

class Toggxy:
    APPID = 'toggxy'
    ICONS = (gtk.STOCK_CANCEL, gtk.STOCK_APPLY)
    MODES = ('none', 'manual')

    def __init__(self):
        self.is_on = True
        self.proxy_setting = Gio.Settings.new("org.gnome.system.proxy")
        self.app = appindicator.Indicator.new(
            self.APPID,
            self.ICONS[self.is_on],
            appindicator.IndicatorCategory.SYSTEM_SERVICES)

        self.app.set_status(appindicator.IndicatorStatus.ACTIVE)
        self.app.set_menu(self.setup_menu())
        gtk.main()

        # Prevents inconsistency.
        self.proxy_setting.set_string('mode', self.MODES[self.is_on])

    def setup_menu(self):
        """Set up GTK menu"""
        menu = gtk.Menu()

        item_toggle = gtk.MenuItem('Toggle')
        item_toggle.connect('activate', self.toggle)
        menu.append(item_toggle)

        item_quit = gtk.MenuItem('Quit')
        item_quit.connect('activate', self.quit)
        menu.append(item_quit)

        menu.show_all()

        return menu

    def toggle(self, _):
        """Toggle proxy setting"""
        self.is_on = not self.is_on
        self.app.set_icon(self.ICONS[self.is_on])
        self.proxy_setting.set_string('mode', self.MODES[self.is_on])

    def quit(self, _):
        """Quit the indicator"""
        gtk.main_quit()

if __name__ == '__main__':
    # Fix SIGINT behavior.
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    _ = Toggxy()
