#!/usr/bin/env bash

################################################################################
#
# unzip-zh
# ========
#
# Simple alias for unzipping files with the infamous Code page 936 encoding,
# which is widely used in M$ world.
#
# @author AnqurVanillapy
# @date 14 May 2017
# @version 0.1.0
################################################################################

if [[ "$#" != "1" ]]; then
    echo "Usage: unzip-zh file" && exit 1
fi

# Phew!
unzip -O cp936 $1
