#!/usr/bin/env bash

################################################################################
#
# xfindx
# ======
#
# An alias for a common way of using `find`.
#
# @author AnqurVanillapy
# @date 6 August 2018
# @version 0.1.0
################################################################################

if [[ "$#" != "1" ]]; then echo "Usage: xfindx NAME" && exit 1; fi

find . -name "*"$1"*"
